name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Commit messager
      run: chmod +x ./scripts/message.sh && ./scripts/message.sh
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'
    - name: build_proto_and_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TOKEN: ${{ secrets.TOKEN }}
      run: chmod +x protogen.sh && ./protogen.sh
